#!/bin/sh

# Notifies user when camera is enabled/disabled in a loop
# dependencies "dunst"

CamDir="/sys/class/video4linux/video0/"
# Icons dir for battery
icon="/usr/share/icons/Adwaita/48x48/status"

while true; do
  # Waits until directory exists/Cam Enabled
  until [ -d "$CamDir" ]
  do
    sleep 1
  done

  # Sends notification
  dunstify --raw_icon=$icon/camera-disabled-symbolic.symbolic.png --urgency=critical "WEBCAM ENABLED"

  # Waits until directory is gone/Cam Disabled
  until [ ! -d "$CamDir" ]
  do
    sleep 1
  done

  dunstify --raw_icon=$icon/camera-disabled-symbolic.symbolic.png --urgency=normal "WEBCAM DISABLED"
done
