#!/bin/bash

eperf_files=(/sys/devices/system/cpu/cpu*/power/energy_perf_bias)

options=("performance" "balance-performance" "normal, default" "balance-power" "power")
epb_values=(0 4 6 8 15)

# Can't cat multiple files?
#all_cores=$(grep -e * -f "${eperf_files[@]}" | awk -F : '{print $2}')
cur_ener=$(cat "${eperf_files[1]}")

# Changes #'s to Options
case "${cur_ener}" in
  (0)  cur_name="performance" ;;
  (4)  cur_name="balance-performance" ;;
  (6)  cur_name="normal, default" ;;
  (8)  cur_name="balance-power" ;;
  (15) cur_name="power" ;;
  (*)  cur_name=$(printf "Value %s [0-15]" "$cur_ener") ;;
esac

num='^[0-9]+$'

# Runs loop to choose performance level
while true; do
    printf 'Please select an option: (Current - %s)\n\n' "$cur_name"
    printf "%s\n" "${options[@]}" | grep -En ".*."
    printf "0:Quit/Exit\n\n"
    read -rp "Enter selection [#s only]: " choice
    case "$choice" in
        0)
            printf "\nUser requested exit\n"
            exit
            ;;
        *)
            if ! [[ $choice =~ $num ]] ; then
	            printf "\n############# \nInvalid entry \n#############\n"
	        else
	            name=$(printf "%s\n" "${epb_values[choice - 1]}")
	            echo "$name" | sudo tee "${eperf_files[@]}" > /dev/null
	            sleep 2
	            # Prints previous one/needs work
	            printf "\nSetting CPU to %s\n" "$cur_name"
	            exit
            fi
            ;;
    esac
done

