#!/bin/bash
# ufetch-arch - tiny system info for arch

## INFO
user=${USER:-$(id -un)}
hostname=${HOSTNAME:-${hostname:-$(hostname)}}
os="$(grep PRETTY_NAME < /etc/os-release | sed -e 's/PRETTY_NAME=//' -e 's/"//g')"
kernel="$(uname -r)"
uptime="$(uptime -p | sed 's/up //')"
packages="$(pacman -Qq | wc -l)"
shell="$(basename "${SHELL}")"

#cpumodel
cpumodel=$(grep 'model name' < /proc/cpuinfo | uniq | cut -c 14-)

#memory
memfree=$(free -h | grep Mem | awk '{print $3}')
memtotal=$(free -h | grep Mem | awk '{print $2}')
mem=$(printf "%s/%s" "$memfree" "$memtotal")

## DEFINE COLORS
# probably don't change these
if [ -x "$(command -v tput)" ]; then
  bold="$(tput bold)"
  black="$(tput setaf 0)"
  red="$(tput setaf 1)"
  green="$(tput setaf 2)"
  yellow="$(tput setaf 3)"
  blue="$(tput setaf 4)"
  magenta="$(tput setaf 5)"
  cyan="$(tput setaf 6)"
  white="$(tput setaf 7)"
  reset="$(tput sgr0)"
fi

# you can change these
lc="${reset}${bold}${cyan}"         # labels
nc="${reset}${bold}${blue}"         # user and hostname
ic="${reset}"                       # info
c0="${reset}${cyan}"                # first color

## OUTPUT
cat <<EOF

${c0}         .         ${nc}${user}${ic}@${nc}${hostname}${reset}
${c0}        / \\        ${lc}OS:    ${ic}${os}${reset}
${c0}       /   \\       ${lc}KERN:  ${ic}${kernel}${reset}
${c0}      /^.   \\      ${lc}UP:    ${ic}${uptime}${reset}
${c0}     /  .-.  \\     ${lc}PKGS:  ${ic}${packages}${reset}
${c0}    /  (   ) _\\    ${lc}SHELL: ${ic}${shell}${reset}
${c0}   / _.~   ~._^\\   ${lc}CPU:   ${ic}${cpumodel}${reset}
${c0}  /.^         ^.\\  ${lc}MEM:   ${ic}${mem}${reset}

EOF
