#!/usr/bin/env sh

## DISPLAYS LISTING OF SSH CLIENTS TO CONNECT TO

# Path to the SSH config file
SSH_CONFIG="$HOME/.ssh/config"

# Read the SSH config file and extract host entries
hosts=$(awk '/^Host / {print $2}' "$SSH_CONFIG")

# Display the available systems
echo "Available systems:"
index=1
for host in $hosts; do
	echo "$index. $host"
	index=$((index + 1))
done

# Prompt for system selection
while true; do
	printf "\nEnter the number of the system to connect to (or 'q' to quit): "
	read -r choice

	case $choice in
	[1-9])
		selected_host=$(echo "$hosts" | awk -v choice="$choice" 'NR == choice')
		ssh "$selected_host"
		break
		;;
	q | Q)
		echo "Exiting."
		exit 0
		;;
	*)
		echo "Invalid option. Please try again."
		;;
	esac
done
