#!/bin/sh

## DISPLAYS LISTING OF SSH CLIENTS TO CONNECT TO

# needs ~/.ssh/config setup before functioning

# pulls 'Host' to display
host=$(awk '/Host / {print $2}' ~/.ssh/config)

# Verifies you typed in a number and not other characters
# Will still error if you type a number that doesn't exist
num='^[0-9]+$'

# Runs loop to ssh into system then reprompts when leaving system
while true; do
  printf "Please select an option:\n\n"
  printf "%s" "$host" | grep -En ".*."
  printf "0:Quit/Exit\n\nEnter selection [#s only]: " >&2
  read -r choice
  case "$choice" in
    0)
      printf "\nUser requested exit\n"
      exit
      ;;
    ''|*[!0-9]*)
      printf "\n############# \nInvalid entry \n#############\n\n"
      ;;
    *)
      name=$(printf "%s" "$host" | head -"$choice" | tail +"$choice")
      ssh "$name"
      ;;
  esac
done
